; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	bblanchon/ArduinoJson@^7.2.0
	olikraus/U8g2@^2.36.0
	arduino-libraries/Ethernet@^2.0.2
build_flags =
	-DCORE_DEBUG_LEVEL=1
	-DPIN_ETH_SCK=12
	-DPIN_ETH_MISO=13
	-DPIN_ETH_MOSI=11
	-DPIN_ETH_CS=10
	-DPIN_ETH_RST=14
	-DPIN_OLED_SDA=8
	-DPIN_OLED_SCL=9
	-DOLED_ADDR=0x3C
	-DUSE_DHCP=0
	-DSTATIC_IP_A=192
	-DSTATIC_IP_B=168
	-DSTATIC_IP_C=99
	-DSTATIC_IP_D=250
	-DSTATIC_GW_D=1
	-DSTATIC_MASK_A=255
	-DSTATIC_MASK_B=255
	-DSTATIC_MASK_C=255
	-DSTATIC_MASK_D=0
	-DURA4_IP_A=192
	-DURA4_IP_B=168
	-DURA4_IP_C=99
	-DURA4_IP_D=3
	-DURA4_PORT=8080
